//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tvt_baikemtragiuaki.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tvtK22CNTT3Lession09Entities : DbContext
    {
        public tvtK22CNTT3Lession09Entities()
            : base("name=tvtK22CNTT3Lession09Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tvtKhoa> tvtKhoa { get; set; }
        public virtual DbSet<tvtSinhVien> tvtSinhVien { get; set; }
    }
}
