//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tvt_baikemtragiuaki.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvtKhoa
    {
        public string tvtMaKH { get; set; }
        public string tvtTenKH { get; set; }
        public Nullable<bool> tvtTrangThai { get; set; }
    }
}
