//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tvt_baikemtragiuaki.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tvtSinhVien
    {
        public string tvtMaSV { get; set; }
        public string tvtHoSV { get; set; }
        public string tvtTenSV { get; set; }
        public Nullable<System.DateTime> tvtNgaySinh { get; set; }
        public string tvtPhai { get; set; }
        public string tvtPhone { get; set; }
        public string tvtEmail { get; set; }
        public string tvtMaKH { get; set; }
    }
}
